name: hi-scooby

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.10.0+cu126
      - tqdm==4.67.3
      - aiohttp==3.13.5
      - alphagenome==0.6.1
      - "alphagenome-research @ git+https://github.com/google-deepmind/alphagenome_research.git@455009019acd4c816873d648404ffef2d506606c"
      - jax==0.10.1
      - jaxlib==0.10.1
      - jax-cuda12-pjrt==0.10.1
      - jax-cuda12-plugin==0.10.1
      - matplotlib==3.10.9
      - numpy==2.4.6
      - scipy==1.17.1
      - scikit-learn==1.8.0
      - pandas==2.3.3
      - pyarrow==24.0.0
      - PyYAML==6.0.3
      - zarr==2.18.7
      - cooler==0.10.4
      - cooltools==0.7.1
      - chex==0.1.91
      - dm-haiku==0.0.16
      - jaxtyping==0.3.10
      - jmp==0.0.4
      - optax==0.2.8
      - orbax==0.1.9
      - orbax-checkpoint==0.11.40
      - absl-py==2.4.0
      - anndata==0.12.16
      - einshape==1.0
      - etils==1.14.0
      - huggingface_hub==1.17.0
      - kagglehub==0.2.5
      - pyBigWig==0.3.25
      - pyfaidx==0.9.0.4
      - pyranges==0.1.4
      - pysam==0.24.0
      - tensorflow==2.21.0
